Jupyter notebook contain both code and rich text elements. Because of the mix of code and text elements, these documents are the ideal place to bring together an analysis description, and its results, as well as, they can be executed perform the data analysis in real time.

In [0]:
# Colab introduction

from google.colab import drive
drive.mount('/content/gdrive')

!wget -cq "https://s3.amazonaws.com/content.udacity-data.com/courses/nd188/\
          flower_data.zip"
!unzip -qq flower_data.zip



**NumPy** is the fundamental package for scientific computing with Python. 
1.   N-dimensional array object
2.   Broadcasting functions
3. Tools for integrating C/C++ and Fortran code



Numpy for matlab users

In [0]:
import numpy as np
print np.spacing(1)	

2.220446049250313e-16


In [0]:
# (1) Create an array and see it's type, shape, and access
# its contents

<type 'numpy.ndarray'>
(3,)
(1, 2, 3)
[5 2 3]
(2, 3)
(1, 2, 4)


**Useful matrices:** Ones, Constant Array, Identity matrix, Random matrix

In [0]:
# (2) Basic stats on matrix: Max of entire matrix, max along each column, each row
a = np.random.rand(5,5)


In [0]:
# Various kinds of Array indexing
print (a)
print (a[-1])
print (a[1,4])
print (a[0:5],a[:5],a[0:5,:])
print (a[-4:])

[[0.18163004 0.1327926  0.9718743  0.21621841 0.94277578]
 [0.05168529 0.52033221 0.03969334 0.59470367 0.65450149]
 [0.33005399 0.99688827 0.79930692 0.23317195 0.18171144]
 [0.24344468 0.7595717  0.74563132 0.39819314 0.30924465]
 [0.94427736 0.33626804 0.49904376 0.5747781  0.72910726]]
[0.94427736 0.33626804 0.49904376 0.5747781  0.72910726]
0.6545014886122122
(array([[0.18163004, 0.1327926 , 0.9718743 , 0.21621841, 0.94277578],
       [0.05168529, 0.52033221, 0.03969334, 0.59470367, 0.65450149],
       [0.33005399, 0.99688827, 0.79930692, 0.23317195, 0.18171144],
       [0.24344468, 0.7595717 , 0.74563132, 0.39819314, 0.30924465],
       [0.94427736, 0.33626804, 0.49904376, 0.5747781 , 0.72910726]]), array([[0.18163004, 0.1327926 , 0.9718743 , 0.21621841, 0.94277578],
       [0.05168529, 0.52033221, 0.03969334, 0.59470367, 0.65450149],
       [0.33005399, 0.99688827, 0.79930692, 0.23317195, 0.18171144],
       [0.24344468, 0.7595717 , 0.74563132, 0.39819314, 0.30924465],
       [0

**Ques** : How do we print a sub array

In [0]:
print(a[1:5][:,2:5])


[[0.03969334 0.59470367 0.65450149]
 [0.79930692 0.23317195 0.18171144]
 [0.74563132 0.39819314 0.30924465]
 [0.49904376 0.5747781  0.72910726]]


In [0]:
a[ 2:5:2,:]
# every other row of a, starting with the third and going to the 5

array([[0.81009874, 0.13646136, 0.46724157, 0.26159925, 0.54689703],
       [0.64855633, 0.9521238 , 0.87069101, 0.62613395, 0.97539296]])

In [0]:
a[ ::2,:]	
# every other row of a, starting with the first


array([[0.18194827, 0.03730236, 0.92103542, 0.3911326 , 0.25323421],
       [0.81009874, 0.13646136, 0.46724157, 0.26159925, 0.54689703],
       [0.64855633, 0.9521238 , 0.87069101, 0.62613395, 0.97539296]])

In [0]:
a[ ::-1,:]
#  a with rows in reverse order

array([[0.64855633, 0.9521238 , 0.87069101, 0.62613395, 0.97539296],
       [0.5077417 , 0.53575225, 0.49967383, 0.34741301, 0.28881767],
       [0.81009874, 0.13646136, 0.46724157, 0.26159925, 0.54689703],
       [0.26373042, 0.56911377, 0.5168187 , 0.34917028, 0.42149399],
       [0.18194827, 0.03730236, 0.92103542, 0.3911326 , 0.25323421]])

In [0]:
# (4) Print evenly spaced values within range
np.arange(3)


array([0, 1, 2])

In [0]:
# (5) Advanced indexing using array
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

# Create an array of indices
b = np.array([0, 1, 0, 2])

# Select one element from each row of a using the indices in b
# Fill here

# Add '1' to element from each row of a using the indices in b
# Fill here

print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [0]:
# (6) Boolean indexing
a = np.array([[1,2], [3, 4], [5, 6]])

# Print all elements greater than 3 in a
# Fill here

bool_idx = (a > 3)   
print(bool_idx)     
print(a[bool_idx])  
# Can you write it more concisely?


[[False False]
 [False  True]
 [ True  True]]
[4 5 6]


array([4, 5, 6])

In [0]:
# (7) Data types
a = np.array([1, 2])


[Link to see various dtypes available with Numpy](https://www.numpy.org/devdocs/user/basics.types.html)

In [0]:
# Array math
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum;
# Fill here

# Elementwise difference; 
# Fill here

# Elementwise product; 
# Fill here

# Elementwise division; 
# Fill here

# Elementwise square root;
# Fill here

In [0]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))

# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [0]:
# Transpose of a matrix, # Matrix multiplication
a= np.random.rand(5,5)
a.transpose()
a.T
np.matmul(a,a)

array([[1.37981973, 1.19502649, 1.42191063, 1.12753065, 2.00390449],
       [0.30089713, 0.19867971, 0.53854145, 0.51488883, 0.60244508],
       [1.60088569, 1.37299889, 1.64363707, 1.06563095, 2.21430254],
       [1.23139987, 0.77345627, 1.56690776, 1.28799197, 1.58193066],
       [1.61784169, 1.15536285, 2.16911198, 1.36009222, 2.33217516]])

**Hands-on** Write code to transpose a matrix without using numpy in-built function

In [0]:
# Hands-0n : Fill the for loop
# Broadcasting: A powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations


# Let's add a vector v to each row of matrix x

x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    # Fill here
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [0]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))   
y = x + vv  # Add x and vv elementwise
print y


[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [0]:
# Can we do better ? Yes; 
# Numpy broadcasting allows us to perform this computation without actually crea-
# ting multiple copies of v. 

x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Rules of Broadcasting


1.  If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.
2. If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.
3. If in any dimension the sizes disagree and neither is equal to 1, an error is raised.





[Very useful link to understand broadcasting](https://jakevdp.github.io/PythonDataScienceHandbook/02.05-computation-on-arrays-broadcasting.html)